### ISSUE TITLE
documentation (README.md/ Wiki) for users/ contributors

### ISSUE THREAD

**Issue by Israel-D** [fccoelho/epigrass#1]
Hi, I, like many, have a lot of time at home.  I am interested in contributing to projects that can help in the crisis we all face.  I would like to help with documentation, but need pointers on where to start, to help your github page become more robust!  Thanks!

**Comment by fccoelho** [comment]
Thanks @Israel-D !

Epigrass can really use an update to its documentation.

I have started a basic README.md. You could start there, by documenting the installation from PyPI.

Then can try to put together a getting started section using one of the demo models included.

I hope this is enough to get you started, if not, keep asking questions!

**Comment by Israel-D** [comment]
Ok, I will try to start working on this ASAP!
I will ask questions if I need, thanks, and stay safe!

**Comment by Israel-D** [comment]
Hi, I think you can use something like pandoc to convert your latex documents into Markdown, so it can be used to build a wiki here!  That would likely save us both effort and time, and make it easier to have your page more robust, and easier to contribute to!

**Comment by fccoelho** [comment]
I already use [sphinx](https://www.sphinx-doc.org/en/master/).
I can configure [readthedocs](https://readthedocs.org/) to automatically pull and compile the documentation as it gets updated.

**Comment by fccoelho** [comment]
readthedocs configured and a link to the automatically compiled latest version of the documentation is added to the README. Now, @Israel-D , if you want to work on the documentation feel free to edit the source `.rst` files and bring them up-to-date.
